# Generated by Django 5.2.6 on 2025-10-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='تاریخ تولد '),
        ),
    ]
