# Generated by Django 5.2.6 on 2025-10-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='pofile_pictures/default.jpg', null=True, upload_to='profile_picutures', verbose_name='عکس پروفایل'),
        ),
    ]
