# Generated by Django 5.2.6 on 2025-11-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_review_options_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظرسنجی', 'verbose_name_plural': 'نظرسنجی\u200cها'},
        ),
    ]
