# Generated by Django 5.2.6 on 2025-11-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/', verbose_name='فایل PDF کتاب'),
        ),
    ]
